#!/usr/bin/env python3
"""Apply the corrected OptiFlow cleanup to a fresh local repository clone.

The script removes only files confirmed to be duplicate/generated/fake legacy
implementations, then copies the cleaned production files into place. It does
not run database migrations, commit Git changes, or delete your repository.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

BUNDLE_DIR = Path(__file__).resolve().parent
REPLACEMENTS = BUNDLE_DIR / 'replacements'

DELETE_PATHS = [
    # Backend secrets, generated bytecode, duplicated database/route layers and
    # destructive demo seed scripts. Their real features are rebuilt in routes.py.
    'optiflow_back/.env.local',
    'optiflow_back/booking_manager.py',
    'optiflow_back/databse.py',
    'optiflow_back/route.py',
    'optiflow_back/seed_db.py',
    'optiflow_back/seed_pitch_data.py',

    # Duplicate Flutter data layers / obsolete models.
    'optiflow_front/lib/core/models/booking.dart',
    'optiflow_front/lib/core/models/job.dart',
    'optiflow_front/lib/core/models/machine.dart',
    'optiflow_front/lib/core/services/supabase_service.dart',
    'optiflow_front/lib/mobile/core/api_service.dart',
    'optiflow_front/lib/mobile/models/job_model.dart',

    # Old whole-job market implementation. External marketplace is now
    # individual manager-approved HUMAN tasks.
    'optiflow_front/lib/mobile/screens/job_market_screen.dart',
    'optiflow_front/lib/mobile/widgets/job_card.dart',
    'optiflow_front/lib/mobile/widgets/machine_card.dart',

    # Duplicate worker implementation. lib/mobile is the one mobile app.
    'optiflow_front/lib/slices/worker',
    'optiflow_front/lib/slices/order',

    # Replaced/non-functional manager UI and fake analytics/settings.
    'optiflow_front/lib/slices/admin/add_machine_screen.dart',
    'optiflow_front/lib/slices/admin/settings_screen.dart',
    'optiflow_front/lib/slices/engine/analytics_screen.dart',
    'optiflow_front/lib/slices/engine/dashboard/widgets/activity_section.dart',
    'optiflow_front/lib/slices/engine/dashboard/widgets/machine_card.dart',
    'optiflow_front/lib/slices/engine/dashboard/widgets/new_job_order.dart',
    'optiflow_front/lib/slices/engine/dashboard/widgets/op_type_chart.dart',
    'optiflow_front/lib/slices/engine/dashboard/widgets/stat_card.dart',
    'optiflow_front/lib/slices/engine/dashboard/widgets/utilization_chart.dart',

    # One-off repair scripts, generated output and stale tests/config.
    'optiflow_front/fix_imports.dart',
    'optiflow_front/fix_imports.py',
    'optiflow_front/fix_strings.py',
    'optiflow_front/run_dashboard.bat',
    'optiflow_front/test/widget_test.dart',
    'optiflow_front/android/build',
    '.idea',
    '.vscode',
]


def remove_path(path: Path) -> bool:
    """Delete one file/directory if it exists and report whether anything changed."""
    if not path.exists() and not path.is_symlink():
        return False
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    else:
        path.unlink()
    return True


def main() -> int:
    """Validate the target repo, remove confirmed junk and copy replacements."""
    target = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path.cwd().resolve()

    if not (target / 'optiflow_back').is_dir() or not (target / 'optiflow_front').is_dir():
        print(f'ERROR: {target} does not look like the OptiFlow repository root.')
        print('Usage: python apply_cleanup.py /path/to/e22-co2060-OptiFlow')
        return 2

    removed = 0
    for relative in DELETE_PATHS:
        removed += int(remove_path(target / relative))

    for cache_dir in list(target.rglob('__pycache__')):
        if cache_dir.is_dir():
            shutil.rmtree(cache_dir)
            removed += 1

    replaced = 0
    for source in REPLACEMENTS.rglob('*'):
        if not source.is_file():
            continue
        relative = source.relative_to(REPLACEMENTS)
        if '__pycache__' in relative.parts or source.suffix in {'.pyc', '.pyo'}:
            continue
        destination = target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        replaced += 1

    print(f'Cleanup applied to: {target}')
    print(f'Removed obsolete/generated paths: {removed}')
    print(f'Created/replaced production files: {replaced}')
    print()
    print('IMPORTANT: run optiflow_back/migrations/001_scheduler_v3.sql in Supabase before starting v3.')
    print()
    print('Validation commands:')
    print('  git diff --stat && git status')
    print('  cd optiflow_back')
    print('  pip install -r requirements-dev.txt')
    print('  pytest -q')
    print('  python -m compileall .')
    print('  cd ../optiflow_front')
    print('  flutter pub get')
    print('  dart format lib test')
    print('  flutter analyze')
    print('  flutter test')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
